### PR TITLE
feat(#136): Adding support for custom proxy

### PR DESCRIPTION
**Pull request by hcf**
Making it possible to specify a custom proxy to be used only when communicating with unleash backend

### CODE REVIEW

**Comment by ivarconr** [comment]
Thanks for the contribution. Looks decent. Will do a proper review next week.

**Review by chriswk — APPROVED** [review]
This looks like a nice extension. Good to see that this allowed you to use the `isProxyAuthenticationByJvmProperties` :)

**Comment by hcf** [comment]
Is anything else needed from my part, or do you merge it into master when you feel it is ready?

**Comment by chriswk** [comment]
We'll wait for a go from @ivarconr as well, but as far as I can see, we don't really need anything else from you. We'll have it merged within this week. Thank you so much for your contribution :)

**Review by ivarconr — APPROVED** [review]
Looks good! 👍🏼

**Pull request merged**
